### ISSUE TITLE
Issue with Old Version of Tool Cache

### ISSUE THREAD

**Issue by djquan** [Azure/k8s-actions#26]
Hello!

I was having some issues getting `setup-kubectl` working properly.  

I kept getting:

```
##[warning]GetStableVersionFailed
##[error]Error: DownloadKubectlFailed
```

when trying to use this basic incantation for it: https://github.com/djquan/k8s-action-repro/blob/master/.github/workflows/main.yml#L18-L20

I tracked down the issue to the use of an out-of-date tool-cache that was using the wrong environment variables.  Specifically, the [version of tool-cache](https://github.com/Azure/k8s-actions/blob/master/node_modules/@actions/tool-cache/lib/tool-cache.js#L32-L33) that this repository is using is looking for `RUNNER_TEMPDIRECTORY` and `RUNNER_TOOLSDIRECTORY`, when the variables in the actual runner are `RUNNER_TEMP ` and `RUNNER_TOOL_CACHE`.  This was updated in tool-cache recently, https://github.com/actions/toolkit/commit/5218a837228e088d1667e8bfdd2a9be78e785690#diff-ecd700b4a481c69908b4b61fc89806ad.

[This reproduction case](https://github.com/djquan/k8s-action-repro/blob/master/.github/workflows/main.yml) should show the correct variables the runner has, the method I eventually used to get `setup-ctl` working, and the error it fails with if the old environment variables are not set.  The results from the checks [are here](https://github.com/djquan/k8s-action-repro/commit/020a2244721f7ad617b72b812ef0df277b2a2a8d/checks).

Apologies if I missed anywhere this behavior was documented.  I did try to update the packages on a fork, but didn't get too far before running into some issues that I couldn't get past. 

Reproduction case:
```yaml
name: Build
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: display env
      run: env | grep RUNNER
    - name: azure with env var
      uses: azure/k8s-actions/setup-kubectl@master
      continue-on-error: true
      env:
        RUNNER_TEMPDIRECTORY: ${RUNNER_TEMP}
        RUNNER_TOOLSDIRECTORY: ${RUNNER_TOOL_CACHE}
    - name: azure without env var
      uses: azure/k8s-actions/setup-kubectl@master
      continue-on-error: true
```
